### ISSUE TITLE
cPickle.UnpicklingError: invalid load key, 'H'

### ISSUE THREAD

**Issue by pamzerbhu** [srama2512/visual-exploration#1]
Thanks for sharing this code, but I meet some mistakes: 

(spl) zd@zd-server:~/code$ /home/zd/anaconda3/envs/spl/bin/python /home/zd/code/visual-exploration/src/look-around/eval.py
Traceback (most recent call last):
  File "/home/zd/code/visual-exploration/src/look-around/eval.py", line 57, in <module>
    loaded_state = torch.load(opts.model_path)
  File "/home/zd/anaconda3/envs/spl/lib/python2.7/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/zd/anaconda3/envs/spl/lib/python2.7/site-packages/torch/serialization.py", line 410, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: invalid load key, 'H'.

I set h5 path and modelnet path as follow:
 parser.add_argument('--model_path', type=str, default='/home/zd/code/visual-exploration/src/look-around/data/ModelNet/lookaround_modelnet10.h5')
  parser.add_argument('--h5_path_unseen', type=str, default='/home/zd/code/visual-exploration/src/look-around/data/SUN360/lookaround.h5')
    
could you help me to solve this problem?

**Comment by srama2512** [comment]
`lookaround_modelnet10.h5` is the dataset path, not the model path. Can you try training a model from scratch and evaluating it? I haven't gotten around to provide the pre-trained models yet.
